config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'maintenances/upload'
  get 'education_degrees/search'
  get 'sections/search'

  resources :enrollments

  resources :students do
    get 'search', on: :collection
  end

  resources :payments do
    get 'new_assign', on: :collection
    get 'pending', on: :collection
    post 'assign', on: :collection
  end

  resources :payment_types

  resources :courses

  resources :student_grades do
    get 'course_grades', on: :collection
    get 'report_card', on: :collection
  end

end

app/models/student.rb
class Student < User
  has_many :student_grades
  has_many :enrollments, ->{ includes :student}
  has_many :sections, through: :enrollments
  has_many :payments
  belongs_to :guardian, foreign_key: :guardian_id

  def current_period_enrollment
    enrollments.where(period_id: Period.current_period).first
#    puts "wan"
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    authorize Student
    @students = if params[:dni]
      Student.where(dni: params[:dni])
    else
      Student.all
    end
  end

  def search
    authorize Student
    @students = Enrollment.joins(:student).where(period_id: Period.current_period, section_id: params[:section_id], state: 1).map(&:student)
  end

  def new
    authorize Student
    @guardian = Guardian.new
    @students = @guardian.students.build
    #@student = Student.new
  end

  def create
    authorize Student
    @guardian = Guardian.new(guardian_params)
    if @guardian.save

      redirect_to students_path
    else
      puts @guardian.errors.inspect
      render :new
    end
  end

  def edit
    authorize Student
    @student = Student.find(params[:id])
  end

  def update
    authorize Student
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def show
    authorize Student
    @student = Student.find(params[:id])
  end

  def guardian_params
    params.require(:guardian).permit(:dni, :p_lastname, :m_lastname, :first_name, :email, :address, :phone, :address,students_attributes: [:dni, :p_lastname, :m_lastname, :first_name, :email, :address, :phone, :_destroy])
  end

  def student_params
    params.require(:student).permit(:dni, :p_lastname, :m_lastname, :first_name, :email, :address, :phone, :address)
  end
end

app/views/students/_form.html.erb
<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">Datos Responsable del alumno / Tutor</div>
    <div class="panel-body">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
            <%= simple_form_for @guardian, url: students_path, wrapper: :horizontal_form, html:{class: "form-horizontal"}  do |f| %>
              <%= f.input :dni, wrapper: "horizontal_dni_search" do %>
                <%= f.input_field :dni, class: "form-control input-sm"%>
                <span class="input-group-btn">
                  <button type="button" class="btn btn-primary btn-sm"><i class="fa fa-search"></i></button>
                </span>
              <%end%>
              <%= f.input :p_lastname %>
              <%= f.input :m_lastname %>
              <%= f.input :first_name %>
              <%= f.input :email %>
              <%= f.input :address%>
              <%= f.input :phone%>
              <%= f.simple_fields_for :students do |s|%>
                <%= render 'student_fields', f: s%>
              <%end%>
              <div class="form-group form-button">
                <div class="col-sm-9 col-sm-offset-3">
                  <%= link_to_add_fields "Agregar Alumno", f, :students %>
                  <%= f.submit 'Guardar', class: "btn btn-sm btn-success" %>
                  <%= link_to 'Cancelar',root_path, class: "btn btn-sm btn-danger" %>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_search.html.erb
<div id="level" class="col-sm-12">
  <%= select_tag "student_id", options_from_collection_for_select(@students, "id","full_name"), include_blank: "Seleccione alumno", class: "select form-control input-sm" %>
</div>

app/views/students/_student_fields.html.erb
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingTwo">
    <h4 class="panel-title">
      <a class="collapsed" role="button" aria-controls="collapseTwo">
        Datos del alumno
      </a>
    </h4>
  </div>
  <div id="collapseTwo" class="panel-collapse" aria-labelledby="headingTwo">
    <div class="panel-body">
      <%= f.input :dni%>
      <%= f.input :p_lastname %>
      <%= f.input :m_lastname %>
      <%= f.input :first_name %>
      <%= f.input :email %>
      <%= f.input :address%>
      <%= f.input :phone%>
      <%= f.hidden_field :_destroy %>
      <div class="form-group">
        <div class="col-sm-3">
          <%= link_to "Eliminar", '#', class: "remove_fields btn btn-sm btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Editar alumno</h2>
    <div class="row">
      <%#= render 'form' %>
      <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">Datos del alumno</div>
          <div class="panel-body">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                  <%= simple_form_for @student, wrapper: :horizontal_form, html:{class: "form-horizontal"}  do |f| %>
                    <%= f.input :dni%>
                    <%= f.input :p_lastname %>
                    <%= f.input :m_lastname %>
                    <%= f.input :first_name %>
                    <%= f.input :email %>
                    <%= f.input :address%>
                    <%= f.input :phone%>
                    <div class="form-group form-button">
                      <div class="col-sm-9 col-sm-offset-3">
                        <%= f.submit 'Actualizar', class: "btn btn-sm btn-success" %>
                        <%= link_to 'Cancelar',root_path, class: "btn btn-sm btn-danger" %>
                      </div>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Reporte de alumnos</h2>
    <!-- Zero Configuration Table -->
    <div class="panel panel-default">
      <div class="panel-heading">Alumnos</div>
      <div class="panel-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap">
          <div class="row">
          <div class="col-sm-6">
            <form class="form-inline" action="/students">
              <div class="form-group">
                <label for="exampleInputName2">D.N.I.</label>
                <input name="dni" type="text" class="form-control input-sm">
              </div>
              <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
            </form></div>
          </div>
          <div class="hr-dashed"></div>
          <div class="row">
            <div class="col-sm-12">
              <table style="width: 100%;" role="grid" class="display table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                  <tr role="row">
                    <th style="width: 147px;" colspan="1" rowspan="1" class="sorting">D.N.I.</th>
                    <th style="width: 243px;" colspan="1" rowspan="1" class="sorting">Alumno</th>
                    <th style="width: 105px;" colspan="1" rowspan="1" class="sorting">Grado</th>
                    <th style="width: 50px;" colspan="1" rowspan="1" class="sorting">Estado</th>
                    <th style="width: 50px;" colspan="1" rowspan="1" class="sorting"></th>
                  </tr>
                </thead>
                <tbody>
                <% @students.each do |student|%>
                  <tr class="odd" role="row">
                    <td><%= student.dni%></td>
                    <td><%= student.full_name%></td>
                    <td><%= student.current_period_enrollment.try(:section).try(:route_name)%></td>
                    <td>
                      <% if student.current_period_enrollment.try(:state)%>
                        <%= student.current_period_enrollment.state==0 ? "Reservado" : "Matriculado" %>
                      <%end%>
                    </td>
                    <td><%= link_to "Detalle", student_path(student), class: "btn btn-primary btn-sm"%></td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Registrar alumno</h2>
    <div class="row">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/students/search.js.erb
$("#student_cont").html("<%=j render('search')%>");
// $("#events").html("<p class='form-control-static'>Seleccione un componente</p>")

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Alumno</h2>
    <div class="row">
      <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">Datos del alumno</div>
          <div class="panel-body">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    <form class="simple_form form-horizontal" >
                      <div class="form-group">
                        <label class="col-sm-3 control-label">DNI</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.dni %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Apellido Paterno</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.p_lastname %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Apellido Materno</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.m_lastname %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.first_name %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Correo electrónico</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.email %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Dirección</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.address %></p>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Teléfono</label>
                        <div class="col-sm-9">
                          <p class="form-control-static"><%= @student.phone %></p>
                        </div>
                      </div>
                      <div class="form-group form-button">
                        <div class="col-sm-9 col-sm-offset-3">
                          <%= link_to 'Editar',edit_student_path(@student), class: "btn btn-sm btn-info" %>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>