config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'maintenances/upload'
  get 'education_degrees/search'
  get 'sections/search'

  resources :enrollments

  resources :students do
    get 'search', on: :collection
  end

  resources :payments do
    get 'new_assign', on: :collection
    get 'pending', on: :collection
    post 'assign', on: :collection
  end

  resources :payment_types

  resources :courses

  resources :student_grades do
    get 'course_grades', on: :collection
    get 'report_card', on: :collection
  end

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  #belongs_to :student, foreign_key: "student_id", class_name: "student"
  #belongs_to :secretary, foreign_key: "secretary_id", class_name: "secretary"
  belongs_to :student
  belongs_to :secretary
  belongs_to :section
  belongs_to :period

  before_validation :set_enrollment_state
  after_create :set_enrollment_payment

  def set_enrollment_payment
    Payment.create(student_id: self.student_id, payment_type_id: PaymentType.for_enrollment.id, period_id: Period.current_period)
    #self.student.payments << Payment.create(payment_type_id: PaymentType.for_enrollment.id, period_id: Period.current_period,)
  end

  def set_enrollment_state
    self.state = 0 unless self.state == 0
  end


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
    authorize Enrollment
    @student = Student.includes(:enrollments).where(:dni => params[:dni])
#    @enrollment = Enrollment.where(student_id: @student.id, period_id: Period.current_period)
  end

  def new
    authorize Enrollment
    @enrollment = Enrollment.new
    @student = Student.find(params[:student_id])
    a = []
    Section.includes(:education_degree => :education_level).each{|v| a <<[[v.education_degree.education_level.name, v.education_degree.name, v.name].join(", "), v.id]}
    @levels =  a
  end

  def create
    authorize Enrollment
    @enrollment = Enrollment.new(enrollment_params.merge({secretary_id: current_user.id, period_id: Period.current_period}))
    if @enrollment.save
      redirect_to enrollments_path(dni: @enrollment.student.dni)
    else
      render :new
    end
    #puts @enrollment.inspect
  end

  def enrollment_params
    params.require(:enrollment).permit(:student_id, :section_id)
  end
end

app/views/enrollments/_form.html.erb
<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">Datos de la reserva del alumno </div>
    <div class="panel-body">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
            <%= simple_form_for @enrollment, wrapper: :horizontal_form, html:{class: "form-horizontal"}  do |f| %>
              <div class="form-group">
                <label class="col-sm-3 control-label">Alumno</label>
                <div class="col-sm-9">
                  <p class="form-control-static"><%= @student.full_name%></p>
                </div>
              </div>
              <%= f.hidden_field :student_id, value: @student.id %>
              <%= f.input :section_id, collection: @levels %>
              <div class="form-group form-button">
                <div class="col-sm-9 col-sm-offset-3">
                  <%= f.submit 'Guardar', class: "btn btn-sm btn-success" %>
                  <%= link_to 'Cancelar',enrollments_path, class: "btn btn-sm btn-danger" %>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Reserva de matricula</h2>
    <!-- Zero Configuration Table -->
    <div class="panel panel-default">
      <div class="panel-heading">Alumnos</div>
      <div class="panel-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap">
          <div class="row">
            <div class="col-sm-6">
              <form class="form-inline" action="/enrollments">
                <div class="form-group">
                  <label for="exampleInputName2">D.N.I.</label>
                  <input name="dni" type="text" class="form-control input-sm">
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
              </form>
            </div>
          </div>
          <div class="hr-dashed"></div>
          <div class="row">
            <div class="col-sm-12">
              <table style="width: 100%;" role="grid" class="display table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                  <tr role="row">
                    <th style="width: 70px;" colspan="1" rowspan="1" class="sorting">DNI</th>
                    <th style="width: 243px;" colspan="1" rowspan="1" class="sorting">Alumno</th>
                    <th style="width: 85px;" colspan="1" rowspan="1" class="sorting">Grado</th>
                    <th style="width: 70px;" colspan="1" rowspan="1" class="sorting">Estado</th>
                    <th style="width: 50px;" colspan="1" rowspan="1" class="sorting"></th>
                  </tr>
                </thead>
                <tbody>
                <% @student.each do |student| %>
                  <tr class="odd" role="row">
                    <td><%= student.dni%></td>
                    <td><%= student.full_name%></td>
                    <td><%= student.current_period_enrollment.try(:section).try(:route_name)%></td>
                    <td>
                    <%if student.current_period_enrollment%>
                      <%= student.current_period_enrollment.state == 0 ? "Reservado" : "Matriculado"%>
                    <%else%>
                      -
                    <%end%>
                    </td>
                    <td>
                    <%if student.current_period_enrollment%>
                      -
                    <%else%>
                      <%= link_to "Reservar", new_enrollment_path(student_id: student.id), class: "btn btn-primary btn-sm"%>
                    <%end%>
                    </td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Reservar matrícula</h2>
    <div class="row">
      <%= render 'form' %>
    </div>
  </div>
</div>