config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'maintenances/upload'
  get 'education_degrees/search'
  get 'sections/search'

  resources :enrollments

  resources :students do
    get 'search', on: :collection
  end

  resources :payments do
    get 'new_assign', on: :collection
    get 'pending', on: :collection
    post 'assign', on: :collection
  end

  resources :payment_types

  resources :courses

  resources :student_grades do
    get 'course_grades', on: :collection
    get 'report_card', on: :collection
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :student
  belongs_to :payment_type
  belongs_to :period

  after_update :add_monthly_payments

  def add_monthly_payments
    if self.payment_type_id == 1
      PaymentType.where("name like 'Mens%'").each do |p|
        Payment.create(student_id: self.student_id, payment_type_id: p.id, period_id: Period.current_period)
        #self.student.payments << Payment.create(payment_type_id: p.id, period_id: Period.current_period)
      end

      Enrollment.where(period_id: Period.current_period, student_id: self.student_id).first.update_attribute(:state, 1)
    end
  end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  validates_presence_of :name, :amount
  scope :for_enrollment, ->{ where(name: "Matricula").first }
  scope :others, ->{ where("name not similar to '(Mat|Men)%'") }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    authorize Payment
    @guardian = Guardian.find(current_user.id)
  end

  def new_assign
    authorize Payment
    #@payment = Payment.new(params[:payment])
    @payment_types = PaymentType.others
    @levels = EducationLevel.all
    #params.require(:enrollment).permit(:student_id, :section_id)
  end

  def assign
    authorize Payment
    group = if params[:payment][:student_id].blank?
              Enrollment.where(section_id: Section.find(params[:payment][:section]),
                period_id: Period.current_period,
                state: 1)
            elsif params[:payment][:section].blank?
              Enrollment.where(state: 1,
                period_id: Period.current_period,
                section_id: EducationGrade.find(params[:payment][:degree]).section_ids)
            elsif params[:payment][:grade].blank?
              Enrollment.where(state: 1,
                period_id: Period.current_period,
                section_id: EducationLevel.find(params[:payment][:level]).education_degrees.includes(:sections).map(&:section_ids).flatten)
            else
              Enrollment.where(student_id: params[:payment][:student_id],
                period_id: Period.current_period,
                state: 1)
            end

    group.each do |student|
      Payment.create(student_id: student.student_id, payment_type_id: params[:payment_type_id])
    end

  end

  def edit
    authorize Payment
    @payment = Payment.find(params[:id])
  end

  def update
    authorize Payment
    @payment = Payment.find(params[:id])
    if @payment.update(pricing_params)

    else
      respond_to do |format|
        format.js
      end
    end
  end

  def pending
    authorize Payment
    #@guardian = Guardian.first
    @guardian = Guardian.find(current_user.id)
  end

  def pricing_params
    params.require(:payment).permit(:op_code, :op_date)
  end
end

app/views/payments/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
  <h4 class="modal-title" id="myModalLabel">Actualizar pago</h4>
</div>
<%= simple_form_for @payment, wrapper: :horizontal_form, html:{class: "form-horizontal"}, remote: true  do |f| %>
  <div class="modal-body">
    <%= f.input :op_code%>
    <%= f.input :op_date, as: :string%>
  </div>
  <div class="modal-footer">
    <%= f.submit 'Guardar', class: "btn btn-sm btn-success" %>
    <%= link_to 'Cancelar',nil, class: "btn btn-sm btn-danger", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/payments/edit.js.erb
$(".modal-content").html("<%=j render('form')%>");

app/views/payments/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Reporte de pagos</h2>
    <!-- Zero Configuration Table -->
    <% @guardian.students.each do |student|%>
    <div class="panel panel-default">
      <div class="panel-heading">Pagos hechos para : <%= student.full_name -%></div>
      <div class="panel-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap">
          <div class="row">
            <div class="col-sm-12">
              <table style="width: 100%;" role="grid" class="display table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                  <tr role="row">
                    <th style="width: 147px;" colspan="1" rowspan="1" class="sorting">Concepto</th>
                    <th style="width: 243px;" colspan="1" rowspan="1" class="sorting">Monto</th>
                    <th style="width: 105px;" colspan="1" rowspan="1" class="sorting">Numero operacion</th>
                    <th style="width: 105px;" colspan="1" rowspan="1" class="sorting">Fecha de pago</th>
                  </tr>
                </thead>
                <tbody>
                <% student.payments.where('op_code is not null').each do |payment|%>
                  <tr class="odd" role="row">
                    <td><%= payment.payment_type.name%></td>
                    <td><%= payment.payment_type.amount%></td>
                    <td><%= payment.op_code%></td>
                    <td><%= payment.op_date%></td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/payments/new_assign.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Registrar concepto de pago</h2>
    <div class="row">
      <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">Datos</div>
          <div class="panel-body">
            <%= simple_form_for :payment, wrapper: :horizontal_form, html:{class: "form-horizontal"}  do |f| %>
              <%= f.input :payment_type, collection: @payment_types%>
              <%#= f.input :level, collection: @levels%>
              <%= f.input :level, collection: @levels, label:"Nivel", include_blank: "Seleccione nivel", input_html:{data: {remote: true, url: education_degrees_search_path}} %>
              <div class="form-group select required payment_level">
                <label class="col-sm-3 control-label">Grado</label>
                <div id="degree_cont" class="col-sm-9">
                  <p class="form-control-static"> - </p>
                </div>
              </div>
              <div class="form-group select required payment_level">
                <label class="col-sm-3 control-label">Sección</label>
                <div id="section_cont" class="col-sm-9">
                  <p class="form-control-static"> - </p>
                </div>
              </div>
              <div class="form-group select required payment_level">
                <label class="col-sm-3 control-label">Alumno</label>
                <div id="student_cont" class="col-sm-9">
                  <p class="form-control-static"> - </p>
                </div>
              </div>
              <%#= f.input :degree, collection: @payment_types%>
              <%#= f.input :section, collection: @payment_types%>
              <%#= f.input :student_id, collection: @payment_types%>
              <div class="form-group form-button">
                <div class="col-sm-9 col-sm-offset-3">
                  <%= f.submit 'Guardar', class: "btn btn-sm btn-success" %>
                  <%= link_to 'Cancelar',root_path, class: "btn btn-sm btn-danger" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/pending.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-title">Pagos pendientes</h2>
    <!-- Zero Configuration Table -->
    <% @guardian.students.each do |student|%>
    <div class="panel panel-default">
      <div class="panel-heading">Pagos pendientes de : <%= student.full_name -%></div>
      <div class="panel-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap">
          <div class="row">
            <div class="col-sm-12">
              <table style="width: 100%;" role="grid" class="display table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                  <tr role="row">
                    <th style="width: 147px;" colspan="1" rowspan="1" class="sorting">Concepto</th>
                    <th style="width: 243px;" colspan="1" rowspan="1" class="sorting">Monto</th>
                    <th style="width: 105px;" colspan="1" rowspan="1" class="sorting"></th>
                  </tr>
                </thead>
                <tbody>
                <% student.payments.where(op_code: nil).each do |payment|%>
                  <tr class="odd" role="row">
                    <td><%= payment.payment_type.name%></td>
                    <td><%= payment.payment_type.amount%></td>
                    <td>
                      <%= link_to "Pagar", edit_payment_path(payment), class: "btn btn-primary btn-sm", data: {toggle: "modal", target: "#myModal", remote: true} %></td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

    </div>
  </div>
</div>

app/views/payments/update.js.erb
<%if @payment.errors.any?%>
	$(".modal-content").html("<%=j render('form')%>");
<%else%>
  window.location.href='<%=j payments_path %>';
	//$(".result_ajax").html("<%#=j render('requirements/index')%>");
  //$(".modal-content").html("");
  //$("#myModal").modal('hide');
<%end%>