config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'maintenances/upload'
  get 'education_degrees/search'
  get 'sections/search'

  resources :enrollments

  resources :students do
    get 'search', on: :collection
  end

  resources :payments do
    get 'new_assign', on: :collection
    get 'pending', on: :collection
    post 'assign', on: :collection
  end

  resources :payment_types

  resources :courses

  resources :student_grades do
    get 'course_grades', on: :collection
    get 'report_card', on: :collection
  end

end

app/models/admin.rb
class Admin < User

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/education_degree.rb
class EducationDegree < ActiveRecord::Base
  belongs_to :education_level
  has_many :sections
end

app/models/education_level.rb
class EducationLevel < ActiveRecord::Base
  has_many :education_degrees
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  #belongs_to :student, foreign_key: "student_id", class_name: "student"
  #belongs_to :secretary, foreign_key: "secretary_id", class_name: "secretary"
  belongs_to :student
  belongs_to :secretary
  belongs_to :section
  belongs_to :period

  before_validation :set_enrollment_state
  after_create :set_enrollment_payment

  def set_enrollment_payment
    Payment.create(student_id: self.student_id, payment_type_id: PaymentType.for_enrollment.id, period_id: Period.current_period)
    #self.student.payments << Payment.create(payment_type_id: PaymentType.for_enrollment.id, period_id: Period.current_period,)
  end

  def set_enrollment_state
    self.state = 0 unless self.state == 0
  end


end

app/models/grade_type.rb
class GradeType < ActiveRecord::Base
end

app/models/guardian.rb
class Guardian < User
  has_many :students, foreign_key: :guardian_id , dependent: :destroy
  accepts_nested_attributes_for :students, allow_destroy: true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :student
  belongs_to :payment_type
  belongs_to :period

  after_update :add_monthly_payments

  def add_monthly_payments
    if self.payment_type_id == 1
      PaymentType.where("name like 'Mens%'").each do |p|
        Payment.create(student_id: self.student_id, payment_type_id: p.id, period_id: Period.current_period)
        #self.student.payments << Payment.create(payment_type_id: p.id, period_id: Period.current_period)
      end

      Enrollment.where(period_id: Period.current_period, student_id: self.student_id).first.update_attribute(:state, 1)
    end
  end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  validates_presence_of :name, :amount
  scope :for_enrollment, ->{ where(name: "Matricula").first }
  scope :others, ->{ where("name not similar to '(Mat|Men)%'") }
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :enrollments
  scope :current_period, ->{ where(bimester: nil).last.id}
end

app/models/programmed_section.rb
class ProgrammedSection < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course
  belongs_to :section
end

app/models/secretary.rb
class Secretary < User

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :education_degree
  has_many :enrollments
  has_many :students, through: :enrollments

  has_many :programmed_sections
  has_many :courses, through: :programmed_sections

  def route_name
    [education_degree.education_level.name, education_degree.name, name].join(" - ")
  end
end

app/models/student.rb
class Student < User
  has_many :student_grades
  has_many :enrollments, ->{ includes :student}
  has_many :sections, through: :enrollments
  has_many :payments
  belongs_to :guardian, foreign_key: :guardian_id

  def current_period_enrollment
    enrollments.where(period_id: Period.current_period).first
#    puts "wan"
  end

end

app/models/student_grade.rb
class StudentGrade < ActiveRecord::Base
  belongs_to :student
  belongs_to :period
  belongs_to :programmed_section
  belongs_to :grade_type
end

app/models/teacher.rb
class Teacher < User
  has_many :programmed_sections
  has_many :courses, through: :programmed_sections
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :p_lastname, :m_lastname
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :dni, :first_name, :p_lastname, :m_lastname, :address, :phone
  before_save :join_lastnames
  before_validation :set_user_password

  self.inheritance_column = :role

  def self.roles
    %w(Admin Student Teacher Secretary Guardian)
  end

  def admin?
    role == "Admin"
  end

  def p_lastname
    last_name ? self.last_name.split(" ")[0] : @p_lastname
  end

  def p_lastname=(val)
    @p_lastname = val
  end

  def m_lastname
    last_name ? self.last_name.split(" ")[1] : @m_lastname
  end

  def m_lastname=(val)
    @m_lastname = val
  end

  def join_lastnames
    self.last_name = [@p_lastname, @m_lastname].join(" ")
  end

  def set_user_password
    self.password = self.dni if self.password.blank?
  end

  def full_name
    [last_name, first_name].join(", ")
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    authorize Course
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    authorize :dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def link_to_add_fields(f, association)
  #   new_object = f.object.class.reflect_on_association(association).klass.new
  #   fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
  #     render(association.to_s.singularize + "_fields", :f => builder, idx: '')
  #   end
  #   link_to_function(('<i class="fa fa-plus"></i> ' + t(:add) + ' ' + new_object.class.model_name.human).html_safe,
  #     "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\", '.add_here')",
  #     class: "btn btn-info btn-rounded  mb-10")
  # end

  def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
   end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-info btn-sm", data: {id: id, fields: fields.gsub("\n", "")})
  end


end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="theme-color" content="#3e454c">

    <title>SACE</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <body>
    <%=render 'layouts/partials/header'%>
    <div class="ts-main-content">
      <%= render 'layouts/partials/sidebar'%>
      <div class="content-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!doctype html>
<html lang="en" class="no-js">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SACE</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'devise' %>
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>

  <body>
    <div class="login-page bk-img">
      <div class="form-content">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%=yield%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/partials/_header.html.erb
  <div class="brand clearfix">
    <a href="index.html" class="logo"><%=image_tag('img/sace.jpg', class: '')%></a>
    <span class="menu-btn"><i class="fa fa-bars"></i></span>
    <%=render 'layouts/partials/profile'%>
  </div>

app/views/layouts/partials/_profile.html.erb
<ul class="ts-profile-nav">
  <li>
    <a href="#"><%= l Time.now, format: :long %></a>
  </li>
  <li class="ts-account">
    <a href="#" style="width:250px;">
      <%=image_tag('img/ts-avatar.jpg', class: 'ts-avatar hidden-side')%>
      <%=current_user.email%> <i class="fa fa-angle-down hidden-side"></i>
    </a>
    <ul>
      <li><a href="#">Mi cuenta</a></li>
      <li><a href="#">Editar cuenta</a></li>
      <li><%= link_to "Cerrar sesion", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </li>
</ul>

app/views/layouts/partials/_sidebar.html.erb
<nav class="ts-sidebar">
  <ul class="ts-sidebar-menu">
    <li class="ts-label"></li>
    <li>
      <%= link_to "/" do%>
        <i class="fa fa-home"></i> Inicio
      <%end%>
    </li>
    <!--nuevo - inicio-->
  <%if policy(Student).create? and policy(Enrollment).create?%>
    <li class="ts-label">Alumno</li>
    <li>
    <%= link_to new_student_path do%>
      <i class="fa fa-child"></i> Registrar alumno
    <%end%>
    </li>
    <li>
    <%= link_to enrollments_path do%>
      <i class="fa fa-check-square-o"></i> Reservar matricula
    <%end%>
    </li>
  <%end%>
  <%if policy(PaymentType).create? or policy(Payment).update?%>
    <li class="ts-label">Pagos</li>
    <%if policy(PaymentType).create? and policy(Payment).assign?%>
    <li>
    <%= link_to new_payment_type_path do%>
      <i class="fa fa-list"></i> Registrar tipo pago
    <%end%>
    </li>
    <li>
    <%= link_to new_assign_payments_path do%>
      <i class="fa fa-money"></i> Registrar concepto de pago
    <%end%>
    </li>
    <%end%>
    <%if policy(Payment).pending?%>
    <li>
    <%= link_to pending_payments_path do%>
      <i class="fa fa-dollar"></i> Pagos pendientes
    <%end%>
    </li>
    <%end%>
  <%end%>
  <%if policy(Student).index? or policy(Payment).index? or policy(StudentGrade).report_card?%>
    <li class="ts-label">Reportes</li>
    <%if policy(Student).index?%>
    <li>
    <%= link_to students_path do%>
      <i class="fa fa-user"></i> Reporte alumnos
    <%end%>
    </li>
    <%end%>
    <%if policy(Payment).index?%>
    <li>
    <%= link_to payments_path do%>
      <i class="fa fa-list-alt"></i> Reporte pagos
    <%end%>
    </li>
    <%end%>
    <%if policy(StudentGrade).report_card?%>
    <li>
    <%= link_to report_card_student_grades_path do%>
      <i class="fa fa-graduation-cap"></i> Reporte notas
    <%end%>
    </li>
    <%end%>
  <%end%>
  <%if policy(StudentGrade).create?%>
    <li class="ts-label">Notas</li>
    <li>
    <%= link_to course_grades_student_grades_path do%>
      <i class="fa fa-sticky-note-o"></i> Registrar notas
    <%end%>
    </li>
  <%end%>
  <%if policy(:maintenance).upload?%>
    <li class="ts-label">Mantenimiento</li>
    <li>
    <%= link_to maintenances_upload_path do%>
      <i class="fa fa-columns"></i> Carga de datos
    <%end%>
    </li>
  <%end%>
    <!--fin-->
    <!-- Account from above -->
    <%= render 'layouts/partials/profile'%>
  </ul>
</nav>